version: '3.8'
services:
    app:
      image: ghcr.io/tmmgroupag/dbi_pyton_service_template-app:latest
      build:
        context: ./app
        target: dbi_pyton_service_template
      expose:
        - "8050"
      restart: always
       
    nginx:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - app
        ports:
            - "${APP_HOST_PORT}:8050"
        restart: always

networks:
  default:
    driver: bridge
    name: dbi_pyton_service_template