name: Create Image and Push to Registry
on:
  push:
    branches:
      - 'master'

jobs:
  createImage:
    name: Create Image and Push to Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dbi_pyton_service_template
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: tmmgroup
          password: ${{ secrets.DBI_PYTHON_SERVICE_TEMPLATE_GIT_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push App
        uses: docker/build-push-action@v3
        with:
          context: ./app
          target: dbi_pyton_service_template
          push: true
          tags: ghcr.io/tmmgroupag/dbi_pyton_service_template:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max